### PR TITLE
fix close inputstream of CITAJService after using it.

### PR DESCRIPTION
**Pull request by yangzhenlong**
fix close inputstream of CITAJService after using it.

### CODE REVIEW

**Review by UDLD — APPROVED** [review]
good

**Comment by rainchen** [comment]
@UDLD  we should merge this after #143 got merged

**Comment by rainchen** [comment]
@yangzhenlong This branch is out-of-date with the base branch
please rebase

**Comment by rainchen** [comment]
@UDLD CI failed the ST tests, please have a check

**Comment by rainchen** [comment]
@yangzhenlong conflicts, please rebase

**Comment by yangzhenlong** [comment]
ok

**Comment by yangzhenlong** [comment]
@rainchen @UDLD this branch has rebased from citahub/develop, please review.

**Review by rainchen — CHANGES_REQUESTED** [review]
CI failed, please fix

**Pull request closed without merging**
