### PR TITLE
fix issue 162，change run test command and update test code

### PR DESCRIPTION
**Pull request by UDLD**

### CODE REVIEW

**Review by rainchen — CHANGES_REQUESTED** [review]
should update your commit message, make it clear what have done

**Comment by UDLD** [comment]
> should update your commit message, make it clear what have done

changed @rainchen

**Review by rainchen — CHANGES_REQUESTED** [review]
should update your `commit message` not only the PR title

**Comment by UDLD** [comment]
> should update your `commit message` not only the PR title

@rainchen  
**changeed to :**   change run test command to adapt to test code change, for fix issue 162

**Comment by yangzhenlong** [comment]
> > should update your `commit message` not only the PR title
> 
> @rainchen
> **changeed to :** change run test command to adapt to test code change, for fix issue 162

Is it better to change to  `fix issue 162 changed running testing command to adapt to changes of testing code`

**Review by rainchen — APPROVED** [review]

**Review by yangzhenlong — APPROVED** [review]

**Pull request merged**
