### PR TITLE
update version and changelog and readme for v20.2.0

### PR DESCRIPTION
**Pull request by UDLD**
1. update version and changelog and readme for v20.2.0
2. change branch of cita_quality
3. add CITA v20.2.0 in test travis ci

### CODE REVIEW

**Comment by UDLD** [comment]
@rainchen  @yangzhenlong  please review

**Comment by rainchen** [comment]
what is release note?

**Comment by rainchen** [comment]
please refer the previous release PR: https://github.com/citahub/cita-sdk-java/pull/152
flow the release flow.

**Comment by UDLD** [comment]
> please refer the previous release PR: #152
> flow the release flow.

added

**Review by yangzhenlong — APPROVED** [review]
Approved

**Review by rainchen — CHANGES_REQUESTED** [review]
please update the PR title

**Review by rainchen — CHANGES_REQUESTED** [review]
PR title is not matching with the base branch name!

**Comment by UDLD** [comment]
> PR title is not matching with the base branch name!

fixed

**Review by yangzhenlong — APPROVED** [review]

**Review by rainchen — APPROVED** [review]

**Pull request merged**
