### PR TITLE
add JDK 11 in travis

### PR DESCRIPTION
**Pull request by UDLD**

### CODE REVIEW

**Review by yangzhenlong — APPROVED** [review]

**Review by rainchen — CHANGES_REQUESTED** [review]
CI failed

**Review by rainchen — CHANGES_REQUESTED** [review]
@UDLD wrong PR title, should be JDK 11

**Comment by UDLD** [comment]
> CI failed

CI passed  @rainchen

**Comment by UDLD** [comment]
> @UDLD wrong PR title, should be JDK 11

fixed

**Review by rainchen — APPROVED** [review]

**Pull request merged**
